SDK docs
matter-labs/zksync-web-v2-docs pull request #112
Opened 2022-10-13 05:01 UTC by krofax

Documentation for Java, Python, and Go SDK's.

2022-10-13 08:27 UTC, uF4No commented on docs/api/go/getting-started.md
> +# Get started
This title should be "Getting started to match the other pages"

2022-10-13 08:28 UTC, uF4No commented on docs/api/go/getting-started.md
> +A few examples are below:
Avoid using passive, should be, "Here are a few examples" or something similar

2022-10-13 08:29 UTC, uF4No commented on docs/api/go/getting-started.md
> +
I'm not familiar with Go but, should we have to include some imports on the top of this script?

2022-10-13 08:30 UTC, uF4No commented on docs/api/java/getting-started.md
> +
Missing intro line like in the Go page "In this guide we will demonstrate how to:"

2022-10-13 08:31 UTC, uF4No commented on docs/api/go/getting-started.md
> +This guide assumes that you are familiar with the basics of go and you have it configured on your local machine.
"you are familiar with the Go programming language", including a link to the Go documentation

2022-10-13 08:32 UTC, uF4No commented on docs/api/java/getting-started.md
> +This guide assumes that you are familiar with the basics of java and you have java configured on your local machine.
"you are familiar with the basics of Java", including a link to the Java documentation. Use capitals

2022-10-13 08:33 UTC, uF4No commented on docs/api/java/getting-started.md
> +For connecting zksync java SDK, just add the following dependency to your build file.
"zkSync" and "Java", let's keep names like this throughout the whole document

2022-10-13 08:57 UTC, uF4No commented on docs/api/python/getting-started.md
> +This guide assumes that you are familiar with the basics of python and you have python configured on your local machine.
Python with capital and link to its docs

2022-10-13 08:59 UTC, uF4No commented on docs/api/python/getting-started.md
> +> It must be compiled by zkSync compiler only!
Maybe add a link to a section in our docs where we mention how to compile contracts

2022-10-13 09:01 UTC, uF4No commented on docs/api/python/getting-started.md
> +To deploy the contract, contract ABI is needed for calling its methods in the standard `web3` way.
Do we need to mention this in this section of the docs that is just about deploying the contract?

2022-10-13 09:04 UTC, uF4No commented
As Ramón mentioned, if the SDKs are not fully tested, I'd consider making this a WIP PR. 
Also, I think once we add these new sections, we'd need to update the [Overview page](https://aqwzx-zksync-v2-docs--pr112-sdk-docs-yj3g7bfj.web.app/api/#sdk)

2022-10-28 10:35 UTC, ramonatmatterlabs requested changes

2022-10-28 10:35 UTC, ramonatmatterlabs commented on docs/api/python/getting-started.md
> +The SDK supports the goerli, and zkSync testnet networks.
I don't think this is true... should support mainnet... please confirm with Max

2022-10-28 11:00 UTC, uF4No commented on docs/.vuepress/config.js
> +          path: "/api/java", // optional, which should be a absolute path.
broken link in menu. Add "/gettting-started" to path

2022-10-28 11:00 UTC, uF4No commented on docs/.vuepress/config.js
> +          path: "/api/python", // optional, which should be a absolute path.
broken link in menu. Add "/gettting-started" to path

2022-10-28 11:00 UTC, uF4No commented on docs/.vuepress/config.js
> +          path: "/api/go", // optional, which should be a absolute path.
broken link in menu. Add "/gettting-started" to path

2022-10-28 11:19 UTC, krofax commented on docs/api/java/getting-started.md
> +For connecting zkSync Java SDK, just add the following dependency to your build file.
It's important to specify "build file", I'd vote that this remains.

2022-10-28 11:26 UTC, ramonatmatterlabs commented
Build file only makes sense for Android with gradle no? On maven projects
for example dependencies lives on a different place

On Fri, Oct 28, 2022, 12:20 Blessing Krofegha ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In docs/api/java/getting-started.md
> <https://github.com/matter-labs/zksync-web-v2-docs/pull/112#discussion_r1007952488>
> :
>
> > @@ -0,0 +1,835 @@
> +# Getting started
> +
> +In this guide we will demonstrate how to:
> +
> +1. Connect to the zkSync network.
> +2. Deposit assets from Ethereum into zkSync.
> +3. Check Balance
> +4. Transfer funds (ERC20 tokens) into the zkSync network
> +5. Withdraw funds (Native coins)
> +
> +## Prerequisite
> +This guide assumes that you are familiar with the basics of [Java programming](https://docs.oracle.com/en/java/) language.
> +
> +##  Installation
> +For connecting zkSync Java SDK, just add the following dependency to your build file.
>
> It's important to specify "build file", I'd vote that this remains.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/matter-labs/zksync-web-v2-docs/pull/112#discussion_r1007952488>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3M3EBWYAK26MMWXXVBV4WLWFOZGHANCNFSM6AAAAAARD4PFEQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-10-28 13:31 UTC, uF4No commented on docs/api/go/getting-started.md
> +In order to interact with smart contract, the SDK needs to know the contract address you want to interact with, as well as its ABI. For that, you need to use ABI.Pack() [method]("https://github.com/e
Remove double quotes from link, it fails

2022-10-28 13:33 UTC, uF4No commented on docs/api/python/getting-started.md
> +URL_TO_ETH_NETWORK = "https://goerli.infura.io/v3/25be7ab42c414680a5f89297f8a11a4d"
Remove Infura URL with API key and replace with "GOERLI_HTTPS_RPC"

2022-10-28 13:33 UTC, uF4No commented on docs/api/python/getting-started.md
> +ZKSYNC_NETWORK_URL = "https://zkSync2-testnet.zkSync.dev"
url should be all lowercase

2022-10-28 13:35 UTC, uF4No commented on docs/api/go/getting-started.md
> +es, err := zksync2.NewEthSignerFromMnemonic("<mnemonic words>", zksync2.ZkSyncChainIdMainnet)
in general, I think we should improve variable names in all code samples. `es` stands for ethereum signer, so let's name it that way. Same with `zp` (zksync provider) or `w` (wallet)

2022-10-28 13:42 UTC, uF4No commented
Can we add a warning on all three new pages mentioning that this section of the docs is still in progress and that it'll be updated with more detailed information?

2022-10-31 14:57 UTC, githubdoramon approved these changes

2022-10-31 14:58 UTC, ramonatmatterlabs approved these changes

2022-10-31 14:58 UTC, merged