Block explorer
matter-labs/zksync-web-v2-docs pull request #124
Opened 2022-10-18 15:24 UTC by krofax

### What I worked on
Added the documentation for everything block explorer which includes:

1. Blocks details on the explorer.
2. Transaction details on the explorer.
3. How to use the search bar.
4. Updated smart contract verification file.
5. Started working on zkEVM docs, but paused, because it's a work in progress on the FE team.

2022-10-18 16:08 UTC, uF4No commented
I think it's confusing that the "Contract Verification" navigation item in the Developer Docs now sends you to the Tools/SDKs > Block explorer. It would be difficult for a user that is not familiar with our docs to understand how to go back to the "Developer Docs".
What do you think if we create a simple page that mentions something like "You can verify the contracts deployed on zkSync using the official block explorer. All the details about how to verify contacts can be found here" (with a link that opens in a new tab). That way we keep users in the same docs section (Developer docs) and it's less confusing. What do you think?

2022-10-18 17:03 UTC, uF4No requested changes

2022-10-18 17:03 UTC, uF4No commented on docs/api/tools/block-explorer/block-view.md
> +However, if you have already left the homepage, you can always search for any Ethereum, DAI, LINK, wBTC, and USDC block by typing in the block number.
I don't think we need to mention tokens here. You can enter a number and you'll search for that specific block regardless of the tokens

2022-10-19 09:28 UTC, krofax commented
> I think it's confusing that the "Contract Verification" navigation item in the Developer Docs now sends you to the Tools/SDKs > Block explorer. It would be difficult for a user that is not familiar with our docs to understand how to go back to the "Developer Docs". What do you think if we create a simple page that mentions something like "You can verify the contracts deployed on zkSync using the official block explorer. All the details about how to verify contacts can be found here" (with a link that opens in a new tab). That way we keep users in the same docs section (Developer docs) and it's less confusing. What do you think?

Totally agree with you.

2022-10-19 13:11 UTC, uF4No approved these changes
Approved

2022-10-21 09:06 UTC, uF4No commented on docs/api/tools/block-explorer/contract-verification.md
> +We recommend using [Hardhat flatten](https://medium.com/coinmonks/flattening-smart-contracts-using-hardhat-dffe7dbc7b3f), [Truffle flattener](https://github.com/NomicFoundation/truffle-flattener) or
Added recommend `hardhat flatten` first

2022-10-21 09:07 UTC, uF4No approved these changes
Approved

2022-10-25 08:09 UTC, uF4No approved these changes
looks good

2022-10-25 09:09 UTC, merged