Add hardhat-zksync-chai-matchers plugin
matter-labs/zksync-web-v2-docs pull request #198
Opened 2022-11-30 12:31 UTC by mpopovac-txfusion

2022-11-30 14:25 UTC, krofax commented on docs/api/hardhat/plugins.md
> +```
This doesn't seem to be live yet.

2022-12-13 12:40 UTC, githubdoramon approved these changes

2022-12-13 18:45 UTC, githubdoramon requested changes

2022-12-13 18:45 UTC, githubdoramon commented on docs/api/hardhat/plugins.md
> +await expect(contract.setAmount(100)).to.emit(token, 'AmountUpdated');
I guess the "token" variable should be "contract" right?

2022-12-14 15:34 UTC, githubdoramon submitted a review, later dismissed

2022-12-15 10:39 UTC, uF4No commented
I think we also need to update the Hardhat Getting started page (/api/hardhat/getting-started.html) where it mentions: "zkSync has three plugins for Hardhat", as now we have 4 😉
Also, it'd be a good idea to also mention this plugin at the end in the Local testing page (api/hardhat/testing.html).

2022-12-15 10:43 UTC, githubdoramon commented
> @mpopovac-txfusion I think we also need to update the Hardhat Getting started page (/api/hardhat/getting-started.html) where it mentions: "zkSync has three plugins for Hardhat", as now we have 4 😉 Also, it'd be a good idea to also mention this plugin at the end in the Local testing page (api/hardhat/testing.html).

Good points @uF4No ... On the getting-started let's not mention # of plugins anymore, let's just say "has the following plugins"

2022-12-15 11:19 UTC, githubdoramon approved these changes

2022-12-15 12:25 UTC, githubdoramon approved these changes

2022-12-15 12:25 UTC, merged