`hardhat-zksync-vyper` docs
matter-labs/zksync-web-v2-docs pull request #76
Opened 2022-07-15 12:57 UTC by ly0va

2022-07-15 14:26 UTC, hedgar2017 requested changes

2022-07-15 14:26 UTC, hedgar2017 commented on docs/api/hardhat/getting-started.md
> +If you are using vyper, check out the [reference](./reference.md#matterlabs-hardhat-zksync-vyper) for our vyper plugin or the [example](https://github.com/matter-labs/hardhat-zksync/tree/main/example
Please capitalize the names of the languages everywhere.

2022-07-15 15:09 UTC, barakshani commented on docs/api/hardhat/getting-started.md
> +If you are using Vyper, check out the [reference](./reference.md#matterlabs-hardhat-zksync-vyper) for our vyper plugin or the [example](https://github.com/matter-labs/hardhat-zksync/tree/main/example
vyper or Vyper?

2022-07-15 15:09 UTC, barakshani commented on docs/api/hardhat/reference.md
> +To use it, you have to install and import both of them.
"you have to install and import both." ?

2022-07-15 15:09 UTC, barakshani commented on docs/api/hardhat/reference.md
> +Add the latest version of this plugin to your project with the following command:
Something in this sentence is missing

2022-07-18 08:03 UTC, perekopskiy approved these changes

2022-07-18 08:23 UTC, merged